language: 
  - cpp
  - node_js

services: docker

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
    - os: linux
      dist: xenial
    - os: windows

before_install:
  - npm install -g cmake-js

jobs:
  include:
    - stage: test
      script: 
        - npm run install
      name: "Install Native Modules"
    - script: npm run test-parsers
      name: "Parser Tests"
    - script: npm run test-types
      name: "Type Tests"
    - script: npm run test-naturality
      name: "Naturality Tests"
    - if: branch = master
      stage: deploy
      before_install: openssl aes-256-cbc -K $encrypted_3858a6b79eca_key -iv $encrypted_3858a6b79eca_iv -in .dropbox_uploader.enc -out ~\/.dropbox_uploader -d
      script: 
        - npm run install
      name: "Install Native Modules"
    - script: npm run build
